name = "dnsjson"
main = "src/index.js"
compatibility_date = "2024-03-04"
workers_dev = false

routes = [
    { pattern = "dnsjson.00z.sh", custom_domain = true },
    { pattern = "dnsjson.00z.sh/*", zone_name = "00z.sh" },
]
